### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by kipusoep** [marcemarc/tooorangey.DictionaryItemKeySearch#1]
Hi,

First of all, nice work!
It would be nice if you could provide a NuGet package too :-)

**Comment by marcemarc** [comment]
Thanks for the reminder, sorry, yes will do.

**Comment by marcemarc** [comment]
finally..... Install-Package tooorangey.uDictionaryItemSearch

**Comment by kipusoep** [comment]
Thanks! :+1:
