### ISSUE TITLE
Error with "View" button

### ISSUE THREAD

**Issue by gordonsaxby** [marcemarc/tooorangey.DictionaryItemKeySearch#6]
I have installed this on Umbraco v7.15.3 and the search seems to work, the Edit button seems to work, but the View button gives the following error:

```
Parser Error
Description: An error occurred during the parsing of a resource required to service this request. Please review the following specific parse error details and modify your source file appropriately.

Parser Error Message: Could not load type 'umbraco.settings.EditDictionaryItem'.

Source Error:


Line 2:  <%@ Register TagPrefix="cc1" Namespace="umbraco.uicontrols" Assembly="controls" %>
Line 3:  
Line 4:  <%@ Page Language="c#" MasterPageFile="../masterpages/umbracoPage.Master" ValidateRequest="false"
Line 5:      CodeBehind="EditDictionaryItem.aspx.cs" AutoEventWireup="True" Inherits="umbraco.settings.EditDictionaryItem" %>
Line 6:  

Source File: /umbraco/settings/editDictionaryItem.aspx    Line: 4
```

**Comment by gordonsaxby** [comment]
Hmm, may have fixed it?

In /App_Plugins/tooorangey.DictionaryItemKeySearch/dictionaryitemkeysearch.controller.js:

Remove lines 43 + 44
            var url = '%252Fumbraco%252Fsettings%252FeditDictionaryItem.aspx%253Fid=' + id;
            top.location = '/umbraco/#/settings/framed/' + url;

Replace with
            top.location = '/umbraco/#/settings/dictionary/edit/' + id;

Seems to work!

**Comment by marcemarc** [comment]
will happily accept a PR.... I didn't think anybody still used this!!!!!

Dan Diplo has a really cool dictionary editor here: https://our.umbraco.com/packages/backoffice-extensions/diplo-dictionary-editor/

but I do still use this on a couple of old sites, where editors search by the 'translation' in order to find the dictionary key...

**Comment by gordonsaxby** [comment]
Going by the description, it doesn't look like the Diplo one can search by Dictionary content, which is what we needed.

**Comment by marcemarc** [comment]
it is it's key USP for crazily disorganised dictionary trees :-P

(it's also quite badly implemented in a 'in memory' search)

If you can PR the change in, I'll do a 'saxby' version release for 7.11+ and update NuGet accordingly

**Comment by marcemarc** [comment]
@gordonsaxby finally released a version of the package on Our and Nuget with your fix!

and then immediately released a version for V8 that is a bit different!
